---
title: "Untitled"
author: "Erica Trinh"
date: "September 18, 2017"
output: 
  github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Loading and preprocessing the data

```{r }
file <- "https://d396qusza40orc.cloudfront.net/repdata%2Fdata%2Factivity.zip"
download.file(file, "/Users/ericatrinh/reproducibleResearchProject1/monitoringData.zip", method="curl")
unzip("/Users/ericatrinh/reproducibleResearchProject1/monitoringData.zip")
activity <- read.csv( "/Users/ericatrinh/reproducibleResearchProject1/activity.csv", header = TRUE)
activity$date <- as.Date( activity$date, format = "%Y-%m-%d") 

```

## What is the average daily activity pattern?


```{r }
data <- activity[ !is.na(activity$steps), ]
totalSteps <- tapply(data$steps, data$date, FUN = sum)
hist(totalSteps, breaks = length(totalSteps), main = "Total Number of Steps", xlab = "Total Steps")
mean(totalSteps, na.rm = TRUE) 
median(totalSteps, na.rm = TRUE)
```

##What is the average daily activity pattern?
```{r }
meanSteps <- tapply(data$steps, data$interval, FUN = mean)
plot(names(meanSteps), meanSteps, type = "l", main = "Average Daily Activity", xlab = "interval" , ylab = "Average Steps" )
names(meanSteps)[match(max(meanSteps), meanSteps)]
```


## Imputing missing values
```{r }
nrow( activity[ is.na(activity$steps), ] )
fill <- as.data.frame( cbind( names(meanSteps), meanSteps) )
fill$meanSteps <- as.numeric(as.character(fill$meanSteps))
# fills in missing data
for( i in 1:nrow(activity) ){
    if( is.na(activity$steps[i]) ){
        activity[i,1] <- round( fill[match(activity$interval[i],fill[,1]),2] )
    }
}
totalSteps <- tapply(activity$steps, activity$date, FUN = sum)
hist(totalSteps, breaks = length(totalSteps), main = "Total Number of Steps", xlab = "Total Steps")
mean(totalSteps, na.rm = TRUE) 
median(totalSteps, na.rm = TRUE)

```

##Are there differences in activity patterns between weekdays and weekends?
```{r}
require(ggplot2)
weekday <- c("Monday", "Tuesday", "Wednesday", "Thursday", "Friday")
weekend <- c("Saturday", "Sunday")
activity<- cbind( activity, Day = weekdays(activity$date) )
levels(activity$Day)[levels(activity$Day) %in% weekday ] <- "weekday"
levels(activity$Day)[levels(activity$Day) %in% weekend ] <- "weekend"
data <- aggregate(steps ~ interval + Day ,activity, FUN = sum )
ggplot( data, aes(interval, steps)) +  geom_line() + facet_wrap(~Day, 2)

```
